git action and sam pipeline build

diff --git a/.github/workflows/doms-ui-cicd.yaml b/.github/workflows/doms-ui-cicd.yaml
--- a/.github/workflows/doms-ui-cicd.yaml
+++ b/.github/workflows/doms-ui-cicd.yaml
@@ -105,3 +105,36 @@ jobs:
       - name: Zip the code and deploy to s3
         run: |
           aws s3 sync ./${{ inputs.build-dir }} s3://${{ secrets.S3_BUCKET_NAME }}
+
+      - name: Invalidate cloudFront cache
+        run: |
+          CLOUDFRONT_INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" | jq -e -n -r 'input.Invalidation.Id')
+          echo "Invalidation Id is: $CLOUDFRONT_INVALIDATION_ID"
+          echo "CLOUDFRONT_INVALIDATION_ID=$CLOUDFRONT_INVALIDATION_ID" >> $GITHUB_ENV
+
+      - name: Wait for completion of cloudfront invalidation
+        id: wait-for-cache-invalidation-completed
+        run: |
+          set +e
+          WAIT_FOR_INVALIDATION_SECONDS=120
+          timeout "$WAIT_FOR_INVALIDATION_SECONDS" /bin/bash -s <<SCRIPT
+            while ! timeout 3 aws cloudfront get-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --id $CLOUDFRONT_INVALIDATION_ID | jq -e -n -r 'input.Invalidation.Status' | grep -q 'Completed'; do
+              echo "Invalidation status of id=$CLOUDFRONT_INVALIDATION_ID is not yet 'Completed', trying again..."
+              sleep 1
+            done
+          SCRIPT
+          if [ "$?" = 0 ]
+          then
+            echo "Invalidation of id=$CLOUDFRONT_INVALIDATION_ID completed"
+            echo "CLOUDFRONT_INVALIDATION_COMPLETED=true" >> $GITHUB_ENV
+          else
+            echo "warning: Invalidation incomplete after waiting for $WAIT_FOR_INVALIDATION_SECONDS seconds, skipping of old artifacts"
+            echo "CLOUDFRONT_INVALIDATION_COMPLETED=false" >> $GITHUB_ENV
+          fi
+          set -e
+
+      - name: Delete previous deployment artifacts
+        if: env.CLOUDFRONT_INVALIDATION_COMPLETED == 'true'
+        run: |
+          aws s3 sync --delete ./${{ inputs.build-dir }} s3://${{ secrets.S3_BUCKET_NAME }}
+
